### PR TITLE
MessagePack Proposal v5 with explicit string type.

### PR DESCRIPTION
**Pull request by chakrit**
Reference: https://gist.github.com/frsyuki/5432559#types-extension-type
GH Issue: https://github.com/creationix/msgpack-js/issues/7

* Reorder decoder types detection code so it aligns with mapping tables in the specs.
* Changed how `undefined` are handled, uses the `fixext 1` extension type instead.
* Removed old `raw`-related things.
* Added support for `str` type family decoded to node string.
* Added support for `bin` type family decoded to node Buffer.
* Added support for `ext` and `fixext` type family decoded to a [type, Buffer] tuple.
  * Exception for `fixext 1` which is just 1-byte long so a simple [type, value] is
    returned instead.
* TODO: There is no test for the `ext` and `fixext` since there is no way/need in JS to
  specify and encode "extension" type. Would be good to have tests on decoding part though
  since other languages/implementation may have made use of them.

### CODE REVIEW

**Comment by doughsay** [comment]
Could this help https://github.com/creationix/msgpack-js/issues/15?

**Comment by creationix** [comment]
@doughsay I would expect that to fix it.  I wonder if @chakrit still wants to merge.

**Comment by creationix** [comment]
@DerGuteWolf see creationix/msgpack-js-browser#6

**Comment by nkzawa** [comment]
:+1:

**Comment by chakrit** [comment]
Wow, I've almost forgotten this PR, it has been so long. Also buried under a pile of other GH notifications.

I'll try to get this mergeable tonight, hopefully.

**Comment by nkzawa** [comment]
@chakrit cool :smile:

**Comment by chakrit** [comment]
@creationix @nkzawa I've merged master back into my fork and gotten rid of the only README conflict.

`npm test` passes but I have lost access to the project that was in need of this so let me know if anything else should be done.

**Pull request merged**
